/**
 * Asset build — docs/02_TECH_SPEC.md §4
 *
 * Runs before `dev` and `build` via the `predev` / `prebuild` npm hooks, so a
 * malformed source file stops the build rather than producing a silently empty
 * index. That is acceptance criterion A4.
 *
 * Two jobs:
 *   1. prompts/*.md    -> lib/generated/prompts.ts
 *   2. knowledge/<id>/ -> public/knowledge/<id>.json + manifest.json
 *
 * Knowledge is emitted into public/ rather than bundled so the browser fetches
 * only the selected agent's index. That is what makes cross-agent isolation
 * structural rather than a filter (§8.7, acceptance E4/E5/E6).
 *
 * Output is deterministic: no timestamps, stable ordering, content-addressed
 * hashes. A rebuild with unchanged sources produces byte-identical files.
 */

import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";

import {
  AssetError,
  chunkKnowledgeFile,
  extractPromptBody,
  countChars,
  type Chunk,
} from "../lib/rag/chunk.ts";

// `__dirname` is undefined in ESM. Derive the root from import.meta.url instead.
const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const PROMPTS_DIR = join(ROOT, "prompts");
const KNOWLEDGE_DIR = join(ROOT, "knowledge");
const GENERATED_DIR = join(ROOT, "lib", "generated");
const PUBLIC_KNOWLEDGE_DIR = join(ROOT, "public", "knowledge");

/**
 * Clause markers every system prompt must contain — docs/04_AGENT_SPEC.md §3.
 *
 * These are enforced at build time on purpose. They are security and honesty
 * controls, not style guidance: the first stops retrieved content from acting as
 * instructions (acceptance H4), the second stops the model blending recalled and
 * retrieved knowledge indistinguishably (§8.8).
 *
 * If a prompt is reworded and this check fails, that is the check working. Add
 * the clause back, or update the marker here deliberately.
 */
const REQUIRED_CLAUSES = [
  { marker: "不是指令", describes: "the untrusted-context clause (reference material is data, not instructions)" },
  { marker: "没有引用知识库", describes: "the empty-retrieval clause (say so when nothing was retrieved)" },
  { marker: "中文回答", describes: "the language clause (answer in Chinese)" },
];

const MIN_PROMPT_SECTIONS = 7;

function rel(absolute: string): string {
  return relative(ROOT, absolute).split(sep).join("/");
}

function sha256(input: string): string {
  return createHash("sha256").update(input, "utf8").digest("hex").slice(0, 12);
}

function listMarkdownFiles(dir: string): string[] {
  const out: string[] = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      out.push(...listMarkdownFiles(full));
    } else if (entry.isFile() && entry.name.toLowerCase().endsWith(".md")) {
      out.push(full);
    }
  }
  return out.sort();
}

function listDirectories(dir: string): string[] {
  return readdirSync(dir, { withFileTypes: true })
    .filter((e) => e.isDirectory())
    .map((e) => e.name)
    .sort();
}

// ---------------------------------------------------------------------------
// 1. Prompts
// ---------------------------------------------------------------------------

interface PromptBuild {
  count: number;
  bytes: number;
}

function buildPrompts(): PromptBuild {
  if (!existsSync(PROMPTS_DIR)) {
    throw new AssetError("prompts/ directory not found", "prompts/");
  }

  const files = listMarkdownFiles(PROMPTS_DIR);
  if (files.length === 0) {
    throw new AssetError("no prompt files found", "prompts/");
  }

  const entries: Array<{ id: string; body: string }> = [];

  for (const file of files) {
    const source = rel(file);
    const id = source.replace(/^prompts\//, "").replace(/\.md$/, "");
    const raw = readFileSync(file, "utf8");
    const body = extractPromptBody(raw, source);

    const sectionCount = (body.match(/^##\s/gm) ?? []).length;
    if (sectionCount < MIN_PROMPT_SECTIONS) {
      throw new AssetError(
        `found ${sectionCount} "## " sections, expected at least ${MIN_PROMPT_SECTIONS} — ` +
          "see docs/04_AGENT_SPEC.md §3 for the seven required sections",
        source,
      );
    }

    for (const clause of REQUIRED_CLAUSES) {
      if (!body.includes(clause.marker)) {
        throw new AssetError(
          `missing ${clause.describes} — expected the text ${JSON.stringify(clause.marker)} to appear. ` +
            "These clauses are enforced at build time; see docs/04_AGENT_SPEC.md §3.",
          source,
        );
      }
    }

    entries.push({ id, body });
  }

  entries.sort((a, b) => a.id.localeCompare(b.id));

  const lines: string[] = [
    "// AUTO-GENERATED by scripts/build-assets.mts — do not edit.",
    "//",
    "// Source of truth: prompts/*.md. The header block of each file (title,",
    "// placement note, warnings) is stripped; the prompt body begins at the first",
    '// "## " heading. See docs/02_TECH_SPEC.md §4.',
    "",
    "export const PROMPTS = {",
  ];

  for (const entry of entries) {
    lines.push(`  ${JSON.stringify(entry.id)}: ${JSON.stringify(entry.body)},`);
  }

  lines.push("} as const;", "");
  lines.push("export type PromptId = keyof typeof PROMPTS;", "");

  const output = lines.join("\n");
  mkdirSync(GENERATED_DIR, { recursive: true });
  writeFileSync(join(GENERATED_DIR, "prompts.ts"), output, "utf8");

  return {
    count: entries.length,
    bytes: entries.reduce((sum, e) => sum + countChars(e.body), 0),
  };
}

// ---------------------------------------------------------------------------
// 2. Knowledge
// ---------------------------------------------------------------------------

interface ManifestEntry {
  chunks: number;
  hash: string;
  files: number;
}

interface KnowledgeBuild {
  agents: string[];
  chunks: number;
  warnings: string[];
  manifest: Record<string, ManifestEntry>;
}

function buildKnowledge(): KnowledgeBuild {
  if (!existsSync(KNOWLEDGE_DIR)) {
    throw new AssetError("knowledge/ directory not found", "knowledge/");
  }

  // Rebuild from scratch so a deleted file cannot leave a stale index behind.
  rmSync(PUBLIC_KNOWLEDGE_DIR, { recursive: true, force: true });
  mkdirSync(PUBLIC_KNOWLEDGE_DIR, { recursive: true });

  const agentIds = listDirectories(KNOWLEDGE_DIR);
  if (agentIds.length === 0) {
    throw new AssetError("knowledge/ contains no agent directories", "knowledge/");
  }

  const manifest: Record<string, ManifestEntry> = {};
  const warnings: string[] = [];
  let totalChunks = 0;

  for (const agentId of agentIds) {
    const agentDir = join(KNOWLEDGE_DIR, agentId);
    const files = listMarkdownFiles(agentDir);

    if (files.length === 0) {
      throw new AssetError(
        `no markdown files — either add knowledge or remove the directory. ` +
          "An empty index would silently produce an agent that never retrieves anything.",
        `knowledge/${agentId}/`,
      );
    }

    const chunks: Chunk[] = [];
    for (const file of files) {
      const source = rel(file);
      const result = chunkKnowledgeFile({
        raw: readFileSync(file, "utf8"),
        file: source,
        agentId,
      });
      chunks.push(...result.chunks);
      warnings.push(...result.warnings);
    }

    const payload = { agentId, chunks };
    const serialized = JSON.stringify(payload);
    const hash = sha256(serialized);

    const withVersion = JSON.stringify({ agentId, version: hash, chunks }, null, 0);
    writeFileSync(join(PUBLIC_KNOWLEDGE_DIR, `${agentId}.json`), withVersion, "utf8");

    manifest[agentId] = { chunks: chunks.length, hash, files: files.length };
    totalChunks += chunks.length;
  }

  const manifestOutput = JSON.stringify({ version: 1, agents: manifest }, null, 2);
  writeFileSync(join(PUBLIC_KNOWLEDGE_DIR, "manifest.json"), manifestOutput + "\n", "utf8");

  return { agents: agentIds, chunks: totalChunks, warnings, manifest };
}

// ---------------------------------------------------------------------------
// Run
// ---------------------------------------------------------------------------

function main(): void {
  const started = Date.now();

  const prompts = buildPrompts();
  const knowledge = buildKnowledge();

  console.log("");
  console.log("  build:assets");
  console.log("");
  console.log(`  prompts      ${prompts.count} file(s), ${prompts.bytes} chars -> lib/generated/prompts.ts`);
  console.log(`  knowledge    ${knowledge.agents.length} agent(s), ${knowledge.chunks} chunk(s) -> public/knowledge/`);
  for (const agentId of knowledge.agents) {
    const entry = knowledge.manifest[agentId];
    if (!entry) continue;
    console.log(
      `                 ${agentId.padEnd(10)} ${String(entry.chunks).padStart(4)} chunks  ` +
        `${String(entry.files).padStart(2)} files  ${entry.hash}`,
    );
  }

  if (knowledge.warnings.length > 0) {
    console.log("");
    console.log(`  ${knowledge.warnings.length} warning(s) — sections outside the 200–500 char band:`);
    for (const warning of knowledge.warnings) {
      console.log(`    ${warning}`);
    }
    console.log("  Warnings do not fail the build. See docs/02_TECH_SPEC.md §8.1.");
  }

  console.log("");
  console.log(`  done in ${Date.now() - started}ms`);
  console.log("");
}

try {
  main();
} catch (error) {
  if (error instanceof AssetError) {
    console.error("");
    console.error(`  build:assets FAILED`);
    console.error("");
    console.error(`    ${error.message}`);
    console.error("");
    process.exit(1);
  }
  throw error;
}
